### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by russkel** [russkel/python-moos#2]
https://travis-ci.com/github/russkel/python-moos/jobs/445116321#L1644
```
MOOSCommObject::SendPkt Exception caught Error sending socket message: Bad file descriptor

1605930046.2350   AsynchronousWriteLoop() catches exception and exits

----
======================================================================

FAIL: test_20_zmsg_types (__main__.pyMOOSTestCase)Exception in DoReading() : remote side closed....

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tests/test.py", line 164, in test_20_zmsg_types

    self.assertTrue(c.is_registered_for('TEST_STRING_VAR'))

AssertionError: False is not true

======================================================================

FAIL: test_33_on_mail_active_queues (__main__.pyMOOSTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tests/test.py", line 352, in test_33_on_mail_active_queues

    self.assertTrue(self.received_mail_q_v1)

AssertionError: False is not true

----------------------------------------------------------------------

Ran 11 tests in 13.043s

FAILED (failures=2)

1605930054.5393 139795917420288-                           disabling nagle

-------------- moos connect ----------------------

  contacting a MOOS server localhost:9000 -  try 00001 

  Handshaking as test_on_mail_active_queuesException in DoReading() : remote side closed....

1605930054.5397 139796192098048-                           disabling nagle

-------------- moos connect ----------------------

  contacting a MOOS server localhost:9000 -  try 00001 

  Handshaking as test_zmsg_types        Exception in hand shaking : remote side closed....--------------------------------------------------

Exception in hand shaking : remote side closed....--------------------------------------------------


```

**Comment by russkel** [comment]
https://travis-ci.com/github/russkel/python-moos/jobs/445116322

```
======================================================================

FAIL: test_33_on_mail_active_queues (__main__.pyMOOSTestCase)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "tests/test.py", line 352, in test_33_on_mail_active_queues

    self.assertTrue(self.received_mail_q_v1)

AssertionError: False is not true
```

**Comment by oviquezr** [comment]
> I think there is something else wrong here. The MacOS test failed for no reason on a CI run which passed after I reran it.

Agreed that there is something odd – I merged the `BASE: ` fix after rebasing and verifying the tests passed, and now they are failing when CI runs under master. Have rerun it 3 times now and I haven't been able to make sense of the failure yet. In one of the runs, it seemed like the subprocess that handled the MOOSDB simply quit, but it hasn't been consistent

**Comment by russkel** [comment]
And before that the Release action didn't complete either: https://github.com/russkel/python-moos/actions/runs/536292725

Okay so we need more visibility into why the subprocess is terminating.

In the meantime I am rerunning the release job. If this actually works then maybe we disable tests for wheel builds, but leave it on for Pip builds until we can get tests reliable in Pip builds.

**Comment by russkel** [comment]
https://pypi.org/project/pymoos/2021.1/#files

Success!
